### PR TITLE
Feature/better faq

### LINKED ISSUE #229: Add to FAQ
Some users are confused by the fact that they do not need to log in to anything. They try to  enter passwords into the  room pin field. 
To Add :

Q:" how can I be sure all students in the room used the system?"
A: "by checking your self in with the blue QR code, you can check the number of users currently checked in."

Q "why can I not log in?"
A "there is no need to log  to use the system.  Login is for  the admin or the contact tracer, not regular users"  

Q "Do I need to login?" 
A"no, not unless you are the admin or the contact tracer"  

Q: "How can i get Corona Tracking Tool  (CTT)N for my organization?"
A: "CTT is open Source. write a mail to the contact address below, or just  go to  Github https://github.com/informatik-mannheim/HSMA-CTT"

### PR DESCRIPTION
**Pull request by emely3h**
The old version of the faq page worked but had some issues:
- It used javascript als template engine and not the actual advantages of thymeleaf als template engine.
- The faq text was stored in one big javaScript array which is very cluttered
- faq dropdown was very unflexible, a link could only be added at the end of the answer. If you wanted to add a link in the middle of the text like in the last question, you had to write the whole html code seperatly so the template engine was not used which means a lot of copied code

To make this better I stored all the text in a seperate xml file, and made a method in the Ct controller to import the data from the xml file and store questions and answers as Strings in a ArrayList. In the faq.html file, thymeleaf loops through the list and creates the collapse button. If you want to add a image/ link,... to an answer you can write between the answer tags html.

If you have questions or suggestions to improve this, reach out.

closes #229

### CODE REVIEW

**Comment by oliverhummel** [comment]
Please resolve the conflicts.

**Comment by oliverhummel** [comment]
pls translate log messages to English

**Comment by oliverhummel** [comment]
I changed the encryption of the mail addresses yesterday, this affected the text of the FAQs as well.

**Comment by emely3h** [comment]
> 
> 
> I changed the encryption of the mail addresses yesterday, this affected the text of the FAQs as well.

Which mail address- I've only updated the faq text, is there something else I need to do?

**Comment by emely3h** [comment]
> pls translate log messages to English

What kind of log messages? System.out.println();? As far as I know there should be no System.out.printlns from me in this pull request.

**Comment by emely3h** [comment]
Somehow there is a major mistake in the code wich makes it break immediatly after trying to run it ("Error creating bean with name 'springSecurityFilterChain'")

I think I did something wrong at some point during the merging. (The pull request has been open for too long and in the meantime many things have changed on the dev branch.)

Since I can't figure out the error I would just close this pull request, delete the branch and open a new one from the current dev branch (since I originally only changed 2 files it's quite easy in this case).
I know this is definitely not best practice but in this case much less effort since I can't figure out what went wrong and how to debug in this case.
Is it ok to do it this way or should I keep looking for what went wrong?

**Comment by Wifi-cable** [comment]
This has Merge conflicts :(  I will have a short look at them.

**Pull request closed without merging**
