### PR TITLE
Feature/raumtypen in datenbank speichern

### PR DESCRIPTION
**Pull request by maxones25**
I have added a new attribute "type" in the class Room. For both import variants I have added the attribute and adjusted the tests

### CODE REVIEW

**Review by emely3h — CHANGES_REQUESTED** [review]

**Comment by oliverhummel** [comment]
closes #92

**Comment by oliverhummel** [comment]
Seems to have a compilation error? Pls fix.

**Comment by maxones25** [comment]
i have fixed the missing import and the merge conflicts.

**Comment by oliverhummel** [comment]
Where are the room types supposed to come from? Especially labs are not so unambiguous in the current room list of TBL.

Pls do not merge until this is clarified.

**Comment by oliverhummel** [comment]
Won't do at the moment.

**Pull request closed without merging**
